### ISSUE TITLE
Error install cenit_google_sheets in Odoo v11

### ISSUE THREAD

**Issue by grethellgarcia** [cenit-io/odoo-integrations#136]
Hello, please your help.

Using Odoo Enterprise v11
When I tried to install, this is the message I get:

Error installing addons cenit_google_sheets v11

I donwload this link  https://www.odoo.com/apps/modules/11.0/cenit_google_sheets/ 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\tools\convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\tools\convert.py", line 338, in _tag_function
    _eval_xml(self, rec, env)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\tools\convert.py", line 194, in _eval_xml
    return odoo.api.call_kw(model, method, args, {})
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\cenit_google_sheets\models\config.py", line 65, in install
    installer.install_common_data(data['data'])
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\cenit_base\models\installer.py", line 726, in install_common_data
    }.get(key, self._install_dummy)(values)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\cenit_base\models\installer.py", line 363, in _install_connection_roles
    type: [(6, False, webhooks)],
UnboundLocalError: local variable 'type' referenced before assignment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\tools\pycompat.py", line 87, in reraise
    raise value
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\service\model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\web\controllers\main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\web\controllers\main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\base\module\module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\base\module\module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\base\module\module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\modules\registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\modules\loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\modules\loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\modules\loading.py", line 181, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\modules\loading.py", line 95, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\tools\convert.py", line 791, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\tools\convert.py", line 852, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\tools\convert.py", line 741, in parse
    self.parse(rec, mode)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\tools\convert.py", line 751, in parse
    exc_info[2]
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\tools\pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\tools\convert.py", line 744, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\tools\convert.py", line 338, in _tag_function
    _eval_xml(self, rec, env)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\tools\convert.py", line 194, in _eval_xml
    return odoo.api.call_kw(model, method, args, {})
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\cenit_google_sheets\models\config.py", line 65, in install
    installer.install_common_data(data['data'])
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\cenit_base\models\installer.py", line 726, in install_common_data
    }.get(key, self._install_dummy)(values)
  File "C:\Program Files (x86)\Odoo 11.0e\server\odoo\addons\cenit_base\models\installer.py", line 363, in _install_connection_roles
    type: [(6, False, webhooks)],
odoo.tools.convert.ParseError: "local variable 'type' referenced before assignment" while parsing file:/c:/program%20files%20(x86)/odoo%2011.0e/server/odoo/addons/cenit_google_sheets/data/data.xml:4, near
<function model="cenit.google_sheets_api_v4.settings" name="install"/>

**Comment by maryguirola** [comment]
Hi @grethellgarcia Thanks for using the module. You can install the module now. We fixed some issues in SpreadSheet collection in Cenit and now is working the installation.
