### ISSUE TITLE
Installed cenit_base module but cannot Install cenit_asana

### ISSUE THREAD

**Issue by omarNIU** [cenit-io/odoo-integrations#30]
# This is My Config File: (Odoo Enterprise v9.0)
[options]
; This is the password that allows database operations:
admin_passwd = xxx
; DATABASE OPTIONS
db_host = localhost
db_port = 5432
db_user = odoo
db_password = xxx
; MISC SETTINGS
; addons_path = /opt/enterprise/enterprise,/opt/odoo/addons,/opt/odoo/custom_modules
addons_path = /opt/odoo/custom_modules,/opt/enterprise/enterprise,/opt/odoo/addons
load = web
timezone = Europe/London
without-demo=all
; LOG SETTINGS
logfile = /var/log/odoo/odoo-server.log
log_handler = werkzeug:WARNING
log_level = warn
no-logrotate = True

# This is the error:
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/enterprise/enterprise/web/controllers/main.py", line 907, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/enterprise/enterprise/web/controllers/main.py", line 895, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 534, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo/openerp/tools/convert.py", line 849, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo/openerp/tools/convert.py", line 932, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 799, in parse
    self.parse(rec, mode)
  File "/opt/odoo/openerp/tools/convert.py", line 802, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/odoo/openerp/tools/convert.py", line 705, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_model.py", line 1165, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/ir/ir_ui_view.py", line 360, in create
    context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 4162, in create
    record = self.browse(self._create(old_vals))
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/odoo/openerp/models.py", line 4359, in _create
    recs._validate_fields(vals)
  File "/opt/odoo/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/models.py", line 1277, in _validate_fields
    raise ValidationError('\n'.join(errors))
ParseError: "Invalid view definition

Error details:
View inheritance may not use attribute 'string' as a selector.

Error context:
View `Asana shared collection settings`
[view_id: 382, xml_id: n/a, model: cenit.asana.settings, parent_id: 3]
None" while parsing /opt/odoo/custom_modules/cenit_asana/view/wizard.xml:5, near
`<record id="wizard_cenit_asana_install" model="ir.ui.view">
            <field name="name">Asana shared collection settings</field>
            <field name="model">cenit.asana.settings</field>
            <field name="inherit_id" ref="base.res_config_installer"/>
            <field name="arch" type="xml">
                <data><form position="attributes">
                    <attribute name="string">Asana shared collection settings</attribute>
                </form>
                <footer position="replace">
                    <footer>
                        <button string="Apply" type="object" name="execute" class="oe_highlight" context="{'install': True}"/>
                    </footer>
                </footer>
                <separator string="title" position="replace">
                    <p class="oe_grey">
                        Configure Asana shared collection data
                    </p>
                    <group>
                        <field name="personal_token" placeholder="Your personal token"/>
                    </group>
                </separator>
            </data></field>
        </record>`

**Comment by omarNIU** [comment]
Just in case anyone else has the same issue: (I am not sure if its a good workaround)

It seems I have sorted the issue by removing the string attribute from cenit_asana/view/wizard.xml from the below lines:
`<button string="Apply" type="object" name="execute" class="oe_highlight" context="{'install': True}"/>`
&
`<separator string="title" position="replace">`

**Comment by sanchojaf** [comment]
Thanks Omar for your feedback

2016-11-26 5:56 GMT-05:00 Omar Tanti <notifications@github.com>:

**Comment by sanchojaf** [comment]
This issue was fixed.
