### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by adamrumjahn** [cenit-io/odoo-integrations#99]
Using Odoo Community 9.0c.  
When I tried to install on a demo database, this is the message I get:

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo_dev/parts/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo_dev/parts/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo_dev/parts/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo_dev/parts/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo_dev/parts/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo_dev/parts/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo_dev/parts/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo_dev/parts/odoo/addons/web/controllers/main.py", line 892, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo_dev/parts/odoo/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo_dev/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo_dev/parts/odoo/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo_dev/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo_dev/parts/odoo/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo_dev/parts/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo_dev/parts/odoo/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo_dev/parts/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo_dev/parts/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo_dev/parts/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo_dev/parts/odoo/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo_dev/parts/odoo/openerp/tools/convert.py", line 934, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo_dev/parts/odoo/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/opt/odoo_dev/parts/odoo/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/odoo_dev/parts/odoo/openerp/tools/convert.py", line 351, in _tag_function
    _eval_xml(self,rec, self.pool, cr, uid, self.idref, context=context)
  File "/opt/odoo_dev/parts/odoo/openerp/tools/convert.py", line 200, in _eval_xml
    res = getattr(model, method)(cr, uid, *args)
  File "/opt/odoo_dev/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo_dev/extra_addons/cenit_slack_1_0_0/models/config.py", line 63, in install
    context = context
  File "/opt/odoo_dev/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo_dev/parts/odoo/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo_dev/extra_addons/cenit_base/models/installer.py", line 550, in get_collection_data
    name, version or "any"
ParseError: "Required 'slack_1_0_0 [0.1]' not found in Cenit
None" while parsing /opt/odoo_dev/extra_addons/cenit_slack_1_0_0/data/data.xml:4, near
<function model="cenit.slack_1_0_0.settings" name="install"/>

**Comment by sanchojaf** [comment]
thanks @innovo3d innovo3d for the notification, checking ...

**Comment by sandryaw06** [comment]
Hi @innovo3d I saw your error. Could you let me see your data.xml details on your path /opt/odoo_dev/extra_addons/cenit_slack_1_0_0/data/data.xml.
if you are also triying to install slack module you can see this video: https://www.youtube.com/watch?v=f6GeWRqcfA0

**Comment by adamrumjahn** [comment]
Hi Sandry, here it is below:

<?xml version="1.0" encoding="utf-8"?>
<openerp>
    <data noupdate="1">
        <function model="cenit.slack_1_0_0.settings" name="install"/>
    </data>
</openerp>

**Comment by adamrumjahn** [comment]
Also, I followed the video when I tried to install (on Version 9)

I noticed that there are currently 2 versions, I tried both and neither installed properly:
https://www.odoo.com/apps/modules/9.0/cenit_slack/
https://www.odoo.com/apps/modules/9.0/cenit_slack_api_1_0_0/  (this is the one that I used in the last install)

**Comment by innovo3d** [comment]
<?xml version="1.0" encoding="utf-8"?>
<openerp>
    <data noupdate="1">
        <function model="cenit.slack_1_0_0.settings" name="install"/>
    </data>
</openerp>

**Comment by innovo3d** [comment]
> <?xml version="1.0" encoding="utf-8"?>
> <openerp>
>     <data noupdate="1">
>         <function model="cenit.slack_1_0_0.settings" name="install"/>
>     </data>
> </openerp>

**Comment by adamrumjahn** [comment]
Apparently I can't paste xml code in Github
<img width="683" alt="screen shot 2017-09-02 at 4 27 41 pm" src="https://user-images.githubusercontent.com/7477099/29998881-b1eebaf8-8ffb-11e7-8c3d-d303302f652b.png">

**Comment by sandryaw06** [comment]
Hi @innovo3d, you must change the model name attribute to cenit.slack_api_1_0_0.settings
....let me know if it works

**Comment by adamrumjahn** [comment]
Still no luck.  Message error below.  I´ll try also on a new installation.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo_dev/parts/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo_dev/parts/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo_dev/parts/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo_dev/parts/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo_dev/parts/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo_dev/parts/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo_dev/parts/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo_dev/parts/odoo/addons/web/controllers/main.py", line 892, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo_dev/parts/odoo/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo_dev/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo_dev/parts/odoo/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo_dev/parts/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo_dev/parts/odoo/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/odoo_dev/parts/odoo/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo_dev/parts/odoo/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/opt/odoo_dev/parts/odoo/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/odoo_dev/parts/odoo/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/odoo_dev/parts/odoo/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/odoo_dev/parts/odoo/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/odoo_dev/parts/odoo/openerp/tools/convert.py", line 934, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/odoo_dev/parts/odoo/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/opt/odoo_dev/parts/odoo/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/odoo_dev/parts/odoo/openerp/tools/convert.py", line 351, in _tag_function
    _eval_xml(self,rec, self.pool, cr, uid, self.idref, context=context)
  File "/opt/odoo_dev/parts/odoo/openerp/tools/convert.py", line 198, in _eval_xml
    model = pool[node.get('model', '')]
  File "/opt/odoo_dev/parts/odoo/openerp/modules/registry.py", line 84, in __getitem__
    return self.models[model_name]
ParseError: "cenit.slack_api_1_0_0.settings" while parsing /opt/odoo_dev/extra_addons/cenit_slack_1_0_0/data/data.xml:4, near
<function model="cenit.slack_api_1_0_0.settings" name="install"/>

**Comment by sandryaw06** [comment]
try to delete the bd again, make a new installation of odoo making sure to download this module (https://www.odoo.com/apps/modules/9.0/cenit_slack_api_1_0_0/) this other one (https://www.odoo.com/apps /modules/9.0/cenit_slack/) is obsolete.
If you have the module cenit_slack_api_1_0_0 you don't need to change the data.xml

**Comment by sanchojaf** [comment]
Hi @innovo3d was possible for you to check the last suggestion of @sandryaw06 ?

**Comment by adamrumjahn** [comment]
Hi guys. I'm going through some backlog of work right now and haven't been able to attend to this problem.  I managed to test it on a demo database and it seems to be working now, but I have yet to test it on my own database. I will look into it again in the next few days.

**Comment by sanchojaf** [comment]
great :+1:, please @innovo3d let us know after your test.

**Comment by Ali-mughal** [comment]
Hi, guys, I want to integrate slack with odoo but found this error <function model="cenit.slack_api_1_0_0.settings" name="install"/> how to resolve it

**Comment by oreju** [comment]
Hello @sanchojaf and @sandryaw06 , 
Sorry for interrupting you. But could you help me to solve issue with client_slack installation. I have received same error when tried to install client_slack module. Module were downloaded from: https://apps.odoo.com/apps/modules/14.0/cenit_slack/

Error message:


```
result = method(recs, *args, **kwargs)
  File "/home/odoodev/git/odoo-appstore/cenit_slack/models/config.py", line 62, in install
    version = COLLECTION_VERSION
  File "/home/odoodev/git/odoo-appstore/cenit_base/models/installer.py", line 661, in get_collection_data
    name, version or "any"
odoo.exceptions.MissingError: Required 'slack_api_1_0_0 [0.1]' not found in Cenit

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoodev/git/odoo/odoo/service/server.py", line 1199, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoodev/git/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoodev/git/odoo/odoo/modules/loading.py", line 457, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoodev/git/odoo/odoo/modules/loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoodev/git/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoodev/git/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoodev/git/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoodev/git/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoodev/git/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/odoodev/git/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoodev/git/odoo/odoo/tools/convert.py", line 685, in _tag_root
    )) from e
odoo.tools.convert.ParseError: while parsing /home/odoodev/git/odoo-appstore/cenit_slack/data/data.xml:4, near
<function model="cenit.slack_api_1_0_0.settings" name="install"/>
```
Thank you for your time!

**Comment by HugOdoo** [comment]
Hello @sanchojaf  and @sandryaw06 

I'm following up on @oreju 's request.

Please let us know,

Thanks,
Hugo
